In [1]:
import numpy as np
np.random.randint(10,size=(4,4))

array([[2, 1, 2, 9],
       [9, 1, 8, 9],
       [4, 3, 9, 1],
       [2, 7, 9, 7]])

In [2]:
import numpy as np
np.random.randint(20,size=(4,4))

array([[ 2, 11, 16, 13],
       [16,  7, 12,  7],
       [17, 13,  0,  0],
       [14, 13, 17,  4]])

In [3]:
b=np.arrange(9.50)
b

AttributeError: module 'numpy' has no attribute 'arrange'

In [4]:
import numpy as np
b=np.arange(9,50)
b

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])