In [1]:
import numpy as np
b=np.random.randint(1,20,8)
print(b)

[12  9 11 15 14 13  8 16]


In [2]:
print(b>10)

[ True False  True  True  True  True False  True]


In [3]:
bool_arr=b>10
print(bool_arr)
new_arr=b[bool_arr]
print(new_arr)

[ True False  True  True  True  True False  True]
[12 11 15 14 13 16]


In [5]:
new_arr=b[b>10]
new_arr

array([12, 11, 15, 14, 13, 16])