In [1]:
import numpy as np

a=[1,2,3]
b=np.array(a)
print(b)
print(type[b])

[1 2 3]
type[array([1, 2, 3])]


In [2]:
a=[1,2,3,'5','a',4.5]
b=np.array(a)
print(b)

['1' '2' '3' '5' 'a' '4.5']


In [3]:
a=[1,2,3,'5',4.5]
b=np.array(a,dtype=float)
print(b)

[1.  2.  3.  5.  4.5]


In [4]:
a=[1,2,3,'5',4.5]
b=np.array(a*3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [5]:
b=np.ones(3)
b


array([1., 1., 1.])

In [6]:
b=np.ones(3,dtype=int)
b

array([1, 1, 1])

In [7]:
b=np.zeros(3)
b

array([0., 0., 0.])

In [8]:
b=np.zeros(3,dtype=int)
b

array([0, 0, 0])

In [9]:
b=np.ones((2,3), dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
b=np.zeros((3,4), dtype=int)
b


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
b=np.full(3)
b

TypeError: full() missing 1 required positional argument: 'fill_value'

In [13]:
b=np.full(3,4,dtype=float)
b

array([4., 4., 4.])

In [14]:
b=np.full((3,3),5,dtype=float)
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [15]:
a=np.empty(4,dtype-int)
print(a)

NameError: name 'dtype' is not defined

In [16]:
a=np.empty(4,dtype=int)
print(a)

[-508300699 2044963551 1399738452 2132968723]


In [17]:
a=np.empty(4,dtype=float)
a


array([0.00000000e+000, 1.38515788e-311, 1.38515788e-311, 1.38515788e-311])