In [1]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
print

NameError: name 'np' is not defined

In [2]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
print(b)

NameError: name 'np' is not defined

In [3]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a,dtype=int)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
